### ISSUE TITLE
Per-peer "Last synced"

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-demo#141]
It would be nice if Connections displayed information about when a peer was last synced with.  It would be a decent way of finding out if you have any dead peers which haven't been up in a long time.  It would also give you an idea of how recent your copy of messages is.

**Comment by arj03** [comment]
Yeah that would be nice. If I remember correctly there is something in EBT you can use for this.

**Comment by KyleMaas** [comment]
Looks like I might be able to get this info from SSB.net.conn.dbPeers().  It has a stateChange timestamp that I *think* I could use for this.

For EBT, I can't seem to figure out how to get information out of it for syncing.  This would be really useful for sync progress, if I could find a way to call it:

https://github.com/ssbc/epidemic-broadcast-trees#ebtprogress

Theoretically, this might expose it, but I can't figure out where this is callable from:

https://github.com/ssbc/ssb-ebt/blob/master/index.js#L110

**Comment by KyleMaas** [comment]
SSB.net.conn.dbPeers() does not give an accurate representation of when we last received data.  It's close, but it's not the information I'm looking for.

**Comment by KyleMaas** [comment]
Trying to listen for a "replicate:finish" event does not seem to yield any results.

**Comment by KyleMaas** [comment]
EBT does track it internally:

https://github.com/ssbc/epidemic-broadcast-trees/blob/master/events.js#L327

**Comment by KyleMaas** [comment]
So, within ssb-ebt, I can get the data I want from `ebt.state.peers[peerId].ts`.  However, ebt is not exposed through ssb-ebt, as far as I can tell.

**Comment by KyleMaas** [comment]
Should be able to get this to work if this was merged and dependencies updated:

https://github.com/ssbc/ssb-ebt/pull/35

**Comment by arj03** [comment]
Please note in browser-core we don't use ssb-ebt directly because it has a wierd interaction with the replication plugin. So you need to change it [here](https://github.com/arj03/ssb-browser-core/blob/793cc80b042d9fd8daac699174c8b8f84586b406/simple-ebt.js#L111) instead. I'm not sure how good this information will be, as I haven't used it for anything, but could be interesting to see. Come to think of it, EBT should have a concept of stalled peers, but looking that up only reveals some tests. Might be a bit of a rabit hole :)
