### ISSUE TITLE
How to verify if my feed is fully synced

### ISSUE THREAD

**Issue by Powersource** [arj03/ssb-browser-demo#6]
So I had [some problem](https://github.com/arj03/ssb-browser-demo/issues/5) with my db so I reset it and started resyncing stuff. But is there any way to verify if I've fully downloaded my feed again, so that I don't fork it? For instance my regular client says that my addon account follows @zozs , but in the addon it says that I can still Follow him. Idk if that's because I'm missing messages or maybe because of some bug.

**Comment by arj03** [comment]
Right, it would probably be good with a mechanism for this. 

If you go to your profile page you should see the last messages. You can also verify the local seq using: SSB.db.last.get().

**Comment by Powersource** [comment]
Hmm ok I think I'm fully synced (checked the db thing) but the following state seems to still be incorrect.

**Comment by arj03** [comment]
The problem actually was that we didn't download contact messages by default, so that was why it was not showing up. I'm working on a few new methods for partial replication that would allow us to get the whole follow graph, but that is currently still WIP. Anyway if you update to the latest version this should be fixed.
